### ISSUE TITLE
ansi_colours dependency introduces LGPL-3.0 code

### ISSUE THREAD

**Issue by matthiasbeyer** [Canop/coolor#3]
Hi! First of all: **I am not a lawyer**.

[This commit](https://github.com/Canop/coolor/commit/7203668228ae4fa44e8dc52b6997fe2416d82609) broke our CI, because `ansi_colour` is introduced as a dependency of this crate.

Problem here is that `ansi_colour` is `LGPL-3.0` licensed. To my understanding, this crate (`coloor`) must be LGPL-3.0 as well now, as well as all crates that depend on `coloor`, because of static linking.

I filed a similar [issue in the termimad repository](https://github.com/Canop/termimad/issues/51) because that's the direct dependency I found [the issue with](https://github.com/TheNeikos/type_description/pull/265).

**Comment by Canop** [comment]
This has been solved a long time ago but I forgot to close the issue
